services:
  gmail_to_weaviate:
    build: .
    volumes:
      - .:/app
      - ./credentials.json:/app/credentials.json
      - ./token.json:/app/token.json
    environment:
      - WEAVIATE_URL=http://weaviate:8080
    depends_on:
      - weaviate

  weaviate:
    image: semitechnologies/weaviate:1.26.4
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
