services:
  gmail_to_weaviate:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./credentials.json:/app/credentials.json
      - ./token.json:/app/token.json
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - weaviate
    command: gunicorn --bind 0.0.0.0:5000 --worker-class eventlet -w 1 app:app

  weaviate:
    image: semitechnologies/weaviate:1.26.4
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
