name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start Weaviate
      run: |
        docker-compose up -d weaviate
        # Wait for Weaviate to be ready
        timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/v1/.well-known/ready)" != "200" ]]; do sleep 5; done' || false
    - name: Run tests
      run: |
        pytest tests/
    - name: Stop Weaviate
      run: docker-compose down
    - name: Lint
      run: flake8 .

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t gmail-to-weaviate .
    - name: Push to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag gmail-to-weaviate ${{ secrets.DOCKER_USERNAME }}/gmail-to-weaviate:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/gmail-to-weaviate:latest
